name: Build and deploy GitHub Pages with screenshot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm build
      - uses: actions/upload-artifact@v4
        with:
          name: out
          path: out

  pages:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: out
          path: out
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v1
        with:
          path: out

  screenshot:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm exec playwright install chromium
      - run: node .github/scripts/screenshot.js
      - uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: .github/screenshot
